CREATE TABLE IF NOT EXISTS EmojiGuilds (
    guildId INTEGER NOT NULL,
    PRIMARY KEY (guildId)
);

CREATE TABLE IF NOT EXISTS Emojis (
    name TEXT NOT NULL,
    emoji TEXT NOT NULL,
    isAnimated INTEGER NOT NULL DEFAULT 0,
    guildId INTEGER NOT NULL,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS Leveling (
    guildId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    xp INTEGER NOT NULL DEFAULT 0,
    messageCount INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (guildId, userId)
);
